version: '3.8'
services:
  angular-app:
    image: karraymahdi/angular:latest
    ports:
      - "4201:80"  # Specify ports as strings
    restart: always  # Restart should be under the service
  prometheus:
    image: prom/prometheusfront
    ports:
      - "9092:9090"  # Specify ports as strings
    volumes:
      - /home/vagrant/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafanafront
    ports:
      - "3002:3000"  # Specify ports as strings
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=esprit
    volumes:
      - grafana_data:/var/lib/grafana
